Development
VVMak/NNGraphix pull request #22
Opened 2024-05-18 22:02 UTC by ElkinIlya

2024-05-18 23:17 UTC, VVMak commented
Можешь, пожалуйста, прилепить issue, которые решил сделать, к этому ПРу?

2024-05-18 23:58 UTC, VVMak commented
Обработка событий становится всё сложнее, нужно придумать, как это лучше обрабатывать.

2024-05-19 00:01 UTC, VVMak requested changes

2024-05-19 00:09 UTC, ElkinIlya commented on frontend/index.html
> +            overflow: hidden
Чтобы убрать скроллбар

2024-05-19 00:11 UTC, ElkinIlya commented on frontend/src/board.rs
> +    #[derivative(Default(value = "4000.0"))]
Это размер svg. Надо его в константу вынести.

2024-05-19 00:12 UTC, ElkinIlya commented on frontend/src/board.rs
> +    #[derivative(Default(value = "0.0"))]
Пока не очень понимаю как там дефолтные значения ставятся. Надо убрать значит.

2024-05-19 00:14 UTC, ElkinIlya commented on frontend/src/board.rs
> +    _window_width: f64,
Хочу там хранить размер окна приложения. Нужно для scale. В зависимости от того где мышка в окне приложения (относительно его центра). В тут сторону приближаемся.

2024-05-19 00:17 UTC, ElkinIlya commented on frontend/src/board/block.rs
> +    pub origin: Coords,
Это первые два поля у ViewBox в svg. В блоке это не нужно (пока во всяком случае). Когда математика меня подводила, думал что нужно их прокинуть. Вроде без этого работает.

2024-05-19 00:18 UTC, ElkinIlya commented on frontend/src/board/block.rs
> +            <rect x={(self.upper_left.x).to_string()} y={(self.upper_left.y).to_string()}
От экспериментов с origin остались)

2024-05-19 00:20 UTC, ElkinIlya commented on frontend/src/board/graph.rs
> +                <defs>
Это сетка. Чтобы красиво было, ну и тестить так удобнее в бесконечной пустоте.

2024-05-19 00:20 UTC, ElkinIlya commented on frontend/src/board/state.rs
> +    DraggingBoard, // TODO: https://github.com/VVMak/NNGraphix/issues/10
Угу

2024-05-19 00:24 UTC, VVMak commented on frontend/src/board.rs
> +    _window_width: f64,
А как оно сейчас работает?

2024-05-19 00:24 UTC, VVMak commented on frontend/src/board/block.rs
> +    pub origin: Coords,
А разве от scale не зависит размер блоков? Как это сейчас работает?

2024-05-19 07:39 UTC, ElkinIlya commented on frontend/src/board.rs
> +                        self.mouse_position.y -= delta.clone().y;
self.mouse_position зависит от self.origin
Когда мы двигаем доску мы меняем self.origin и надо менять self.mouse_position
Когда мы просто двигаем мышку self.origin не меняется
Короче пока оно работает - лучше не трогать

2024-05-20 05:52 UTC, VVMak commented on frontend/src/board.rs
> +                        self.mouse_position.y -= delta.clone().y;
А, т.е. будем трогать, когда будет больше кода, и будет больший риск набагать?

2024-05-20 18:41 UTC, VVMak requested changes

2024-05-20 18:41 UTC, VVMak commented on frontend/src/board/graph.rs
> +                <defs>
Вынеси сетку в Board из Graph отдельную функцию, зависящую от шага сетки, и с соответствующей константой

2024-05-20 18:41 UTC, VVMak commented on frontend/src/board.rs
> +    start_mouse_position: Vector, // position where rectangle selection started
это поле должно лежать в State::RectangleSelection

2024-05-20 18:41 UTC, VVMak commented on frontend/src/board/state.rs
> +    RectangleSelection,
RectangleSelection(Vector)

2024-05-20 18:41 UTC, VVMak commented on frontend/src/board.rs
> +                    State::RectangleSelection => {
RectangleSelection(start)

2024-05-20 18:41 UTC, VVMak commented on frontend/src/board.rs
> +                    if self.state == State::RectangleSelection {
if let State::RectangleSelection(start) == self.state {

2024-05-20 18:41 UTC, VVMak commented on frontend/src/board/vector.rs
> +}
github ругается, что пустой строчки в конце нет)

2024-05-20 18:41 UTC, VVMak commented on frontend/src/board/graph.rs
> +    pub fn draw_selection_rect(&self, corner_one: Vector, corner_two: Vector) -> Html {
вынеси в board, self не используется

2024-05-20 18:50 UTC, VVMak commented on frontend/src/board.rs
> +    let top_left_one = Vector{x: first_rect_one.x.min(first_rect_two.x), y: first_rect_one.y.min(first_rect_two.y)};
Сделай функцию, которая берёт "прямоугольник" и возвращает его верхнюю левую и нижнюю правую точки в tuple.
Сможешь заюзать её тут 2 раза, будет проще выглядеть.

2024-05-20 20:03 UTC, VVMak commented on frontend/src/board.rs
> -                    }
зачем эти изменения?
теперь при ctrl+click по выделенному не будет сниматься выделение с уже выделенных блоков

2024-05-20 20:41 UTC, VVMak requested changes

2024-05-20 20:41 UTC, VVMak commented on frontend/src/board.rs
> +                            let bottom_right = Vector {x: top_left.x.clone() + Block::get_block_width(),
Можно сделать
`= top_left + get_block_size()`
добавив метод `get_block_size()` возврата размера в виде вектора

2024-05-20 20:41 UTC, VVMak commented on frontend/src/board.rs
> +        let screen_space_mouse_position = (self.mouse_position.clone() - self.origin.clone()) / self.board_size.clone() * BASE_BOARD_SIZE;
Во всех арифметических операциях у тебя self.board_size делится на BASE_BOARD_SIZE.
Мб тогда хранить само отношение и назвать не board_size, а что-нибудь типа self.board_scale ?

2024-05-20 20:41 UTC, VVMak commented on frontend/src/board.rs
> +                        for block in self.graph.get_blocks() {
Во-первых, можно было проитерироваться по (k, v), и не пришлось бы обращаться через `.0` или `.1`.
Во-вторых, раз уж мы пробегаемся всё равно по всем блоками, то лучше сначала сделать `clear_selection()`, а потом просто набрать те, с которыми есть пересечения.
И в-третьих, сделай метод внутри `Graph` типа update_selection_rect с 2 аргументами - верхняя левая и нижняя правая точки прямоугольного выделения, а возвращать он будет HashSet из того, что выделил.
Тогда можно удалить и `Graph.get_blocks()`, и `block.is_selected()`.

2024-05-21 07:32 UTC, VVMak requested changes

2024-05-21 07:32 UTC, VVMak commented on frontend/src/board.rs
>  #[derive(Default)]
#[derive(Default)]
Всё ещё лишнее вроде.

2024-05-21 07:32 UTC, VVMak commented on frontend/src/board.rs
> +            + self.origin.clone();
Выглядит, будто ты в результате просто сделал `self.mouse_position = self.mouse_position`

2024-05-21 07:32 UTC, VVMak commented on frontend/src/board.rs
> +                    if !e.ctrl_key() && !self.selected.contains(&id) {
зачем эти изменения (и 2 строчками ниже)? (в тг обсудим)

2024-08-02 17:16 UTC, VVMak approved these changes

2024-08-02 17:16 UTC, merged